/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HuffmanGUI;

import Ascii.Ascii;
import Process.CaracterComparator;
import Process.Huffman;
import Process.Nodo;
import java.awt.Color;
import java.io.*;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.hyperic.sigar.CpuPerc;
import org.hyperic.sigar.Sigar;
import org.hyperic.sigar.SigarException;

/**
 *
 * @author The Worst One
 */
public class home extends javax.swing.JFrame {
    
    private Huffman huffman;
    private Ascii ascii;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.getContentPane().setBackground(new Color(0, 153, 153));
        setLocationRelativeTo(null);
        huffman = new Huffman();
        ascii = new Ascii();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FileName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        AsciiCmp = new javax.swing.JButton();
        HuffmanCmp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Descomprimir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Frecuency = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CodeH = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CodeA = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        I3H = new javax.swing.JLabel();
        D1O = new javax.swing.JLabel();
        I2H = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        I3A = new javax.swing.JLabel();
        I2A = new javax.swing.JLabel();
        I1A = new javax.swing.JLabel();
        I1H = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 198, 200));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de Compresion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FileName.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        FileName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(FileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 219, 42));

        jPanel2.setBackground(new java.awt.Color(124, 154, 198));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Escoga el método de Compresión", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP));

        AsciiCmp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        AsciiCmp.setText("ASCII");
        AsciiCmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsciiCmpActionPerformed(evt);
            }
        });

        HuffmanCmp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        HuffmanCmp.setText("Huffman");
        HuffmanCmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuffmanCmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HuffmanCmp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(AsciiCmp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsciiCmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuffmanCmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 230, 90));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre del Archivo: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 148, 27));

        Descomprimir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Descomprimir.setText("Descomprimir");
        Descomprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescomprimirActionPerformed(evt);
            }
        });
        jPanel1.add(Descomprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, 40));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Compress", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(102, 0, 102));
        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 640, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ASCII File");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 110, 27));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Razón de Compresión ( (D-d)/D ):  ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 27));

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista Frecuencia", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Frecuency.setEditable(false);
        Frecuency.setColumns(20);
        Frecuency.setRows(5);
        Frecuency.setOpaque(false);
        jScrollPane1.setViewportView(Frecuency);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 360, 110));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 10, 220));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Original File");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 148, 27));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Huffman File");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, 27));

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caracter                                                Código Prefijo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        CodeH.setEditable(false);
        CodeH.setColumns(20);
        CodeH.setRows(5);
        CodeH.setOpaque(false);
        jScrollPane2.setViewportView(CodeH);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 320, 100));

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caracter                                                 Código Prefijo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        CodeA.setEditable(false);
        CodeA.setColumns(20);
        CodeA.setRows(5);
        CodeA.setOpaque(false);
        jScrollPane3.setViewportView(CodeA);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Peso: ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 27));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Memoria JVM:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 27));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Peso: ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, 27));

        I3H.setBackground(new java.awt.Color(204, 255, 204));
        I3H.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        I3H.setOpaque(true);
        jPanel3.add(I3H, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 80, 20));

        D1O.setBackground(new java.awt.Color(204, 255, 204));
        D1O.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        D1O.setOpaque(true);
        jPanel3.add(D1O, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, 20));

        I2H.setBackground(new java.awt.Color(204, 255, 204));
        I2H.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        I2H.setOpaque(true);
        jPanel3.add(I2H, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 80, 20));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Peso: ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 110, 27));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Razón de Compresión ( (D-d)/D ):  ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 230, 27));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Memoria JVM:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 110, 27));

        I3A.setBackground(new java.awt.Color(204, 255, 204));
        I3A.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        I3A.setOpaque(true);
        jPanel3.add(I3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 80, 20));

        I2A.setBackground(new java.awt.Color(204, 255, 204));
        I2A.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        I2A.setOpaque(true);
        jPanel3.add(I2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 80, 20));

        I1A.setBackground(new java.awt.Color(204, 255, 204));
        I1A.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        I1A.setOpaque(true);
        jPanel3.add(I1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 80, 20));

        I1H.setBackground(new java.awt.Color(204, 255, 204));
        I1H.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        I1H.setOpaque(true);
        jPanel3.add(I1H, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsciiCmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsciiCmpActionPerformed
        try {
            ascii.compressAscii(FileName.getText());
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        Map <String, String> codigoPrefijo = ascii.getCodigoPrefijo();
        //List <Nodo> sublist = huffman.getFrecuencias().subList(huffman.getFrecuencias().size()-3, huffman.getFrecuencias().size());
        
        CodeA.setText("");
        for (String codigo: codigoPrefijo.keySet()){
            CodeA.append(codigo+"\t\t"+codigoPrefijo.get(codigo)+"\n\n");
        }
        
        D1O.setText(String.valueOf(ascii.getOriginalAsciiLen())+ " KB");
        
        I1A.setText(String.valueOf(ascii.getOriginalAsciiLen())+" KB");
        I2A.setText(String.format("%.2f ",(float)(ascii.getOriginalAsciiLen()-ascii.getOriginalAsciiLen())*100/ascii.getOriginalAsciiLen())+"%" );
        I3A.setText(String.valueOf( (Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory())/(1024*1024) )+" MB");
        
    }//GEN-LAST:event_AsciiCmpActionPerformed

    private void HuffmanCmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuffmanCmpActionPerformed
        try {
            huffman.compressHuffman(FileName.getText());
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "El archivo no existe!");
        }
        String caracteres = "";
        String frecuencias = "";
        for (Nodo clave: huffman.getFrecuencias()){
            caracteres += (clave.getClave().equals("\n")?"\\n":clave.getClave()) + "\t";
            frecuencias += clave.getFrecuencia() +"\t";
        }
        caracteres += "\n"; frecuencias += "\n";
        Frecuency.setText("\n"+caracteres+frecuencias);
        
        Map <String, String> codigoPrefijo = huffman.getCodigoPrefijo();
        //List <Nodo> sublist = huffman.getFrecuencias().subList(huffman.getFrecuencias().size()-3, huffman.getFrecuencias().size());
        
        CodeH.setText("");
        for (String codigo: codigoPrefijo.keySet()){
            CodeH.append(codigo+"\t\t"+codigoPrefijo.get(codigo)+"\n\n");
        }
        
        
        
        D1O.setText(String.valueOf(ascii.getOriginalAsciiLen())+ " KB");
        I1H.setText(String.valueOf(huffman.getHuffmanAsciiLen())+" KB");
        //I1H.setText(String.valueOf(huffman.getOriginalLen())+" KB");
        //I2H.setText(String.format("%.2f ",(float)(huffman.getOriginalLen()-huffman.getDatLen())*100/huffman.getOriginalLen())+"%" );
        I2H.setText(String.format("%.2f ",(float)(ascii.getOriginalAsciiLen()-huffman.getHuffmanAsciiLen())*100/ascii.getOriginalAsciiLen())+"%" );
        /*try {
            I3H.setText(CpuPerc.format(sigar.getCpuPerc().getUser()));
        } catch (SigarException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        I3H.setText(String.valueOf( (Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory())/(1024*1024) )+" MB");
    }//GEN-LAST:event_HuffmanCmpActionPerformed

    private void DescomprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescomprimirActionPerformed
        
        try {
            ObjectInputStream entrada=new ObjectInputStream(new FileInputStream(FileName.getText()+"RAIZ.obj"));
            Nodo raiz = (Nodo) entrada.readObject();
            huffman.descompress(raiz, FileName.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "El archivo no existe!");
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("\nSe descomprimio con exito el archivo!");
    }//GEN-LAST:event_DescomprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsciiCmp;
    private javax.swing.JTextArea CodeA;
    private javax.swing.JTextArea CodeH;
    private javax.swing.JLabel D1O;
    private javax.swing.JButton Descomprimir;
    private javax.swing.JTextField FileName;
    private javax.swing.JTextArea Frecuency;
    private javax.swing.JButton HuffmanCmp;
    private javax.swing.JLabel I1A;
    private javax.swing.JLabel I1H;
    private javax.swing.JLabel I2A;
    private javax.swing.JLabel I2H;
    private javax.swing.JLabel I3A;
    private javax.swing.JLabel I3H;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
